import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Providers from "../providers";

const inter = Inter({
   subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
         <Providers>
            <main className="max-w-7xl mx-auto px-4 py-8">
               <Header/>
            {children}
         </main>
        </Providers>
      </body>
    </html>
  );
}
