export type IngredientItem = {
  id: number;
  name: string;
  category: string;
};

export const ingredients: IngredientItem[] = [
  { id: 1, name: "Eggs", category: "Dairy" },
  { id: 2, name: "Milk", category: "Dairy" },
  { id: 3, name: "Flour", category: "Grain" },
  { id: 4, name: "Sugar", category: "Sweetener" },
  { id: 5, name: "Salt", category: "Spice" },
  { id: 6, name: "Butter", category: "Dairy" },
  { id: 7, name: "Olive Oil", category: "Oil" },
  { id: 8, name: "Vegetable Oil", category: "Oil" },
  { id: 9, name: "Garlic", category: "Other" },
  { id: 10, name: "Onion", category: "Other" },
  { id: 11, name: "Tomato", category: "Vegetable" },
  { id: 12, name: "Potato", category: "Vegetable" },
  { id: 13, name: "Carrot", category: "Vegetable" },
  { id: 14, name: "Bell Pepper", category: "Vegetable" },
  { id: 15, name: "Cucumber", category: "Vegetable" },
  { id: 16, name: "Chicken Breast", category: "Meat" },
  { id: 17, name: "Ground Beef", category: "Meat" },
  { id: 18, name: "Pasta", category: "Grain" },
  { id: 19, name: "Rice", category: "Grain" },
  { id: 20, name: "Cheese", category: "Dairy" },
  { id: 21, name: "Yogurt", category: "Dairy" },
  { id: 22, name: "Baking Powder", category: "Other" },
  { id: 23, name: "Vanilla Extract", category: "Spice" },
  { id: 24, name: "Cinnamon", category: "Spice" },
  { id: 25, name: "Honey", category: "Sweetener" },
  { id: 26, name: "Lemon", category: "Fruit" },
  { id: 27, name: "Lime", category: "Fruit" },
  { id: 28, name: "Basil", category: "Spice" },
  { id: 29, name: "Parsley", category: "Spice" },
  { id: 30, name: "Dill", category: "Spice" },
  { id: 31, name: "Oregano", category: "Spice" },
  { id: 32, name: "Thyme", category: "Spice" },
  { id: 33, name: "Soy Sauce", category: "Sauce" },
  { id: 34, name: "Mayonnaise", category: "Sauce" },
  { id: 35, name: "Ketchup", category: "Sauce" },
  { id: 36, name: "Mustard", category: "Sauce" },
  { id: 37, name: "Corn", category: "Vegetable" },
  { id: 38, name: "Green Peas", category: "Vegetable" },
  { id: 39, name: "Broccoli", category: "Vegetable" },
  { id: 40, name: "Spinach", category: "Vegetable" },
  { id: 41, name: "Zucchini", category: "Vegetable" },
  { id: 42, name: "Mushrooms", category: "Vegetable" },
  { id: 43, name: "Chili Pepper", category: "Vegetable" },
  { id: 44, name: "Coconut Milk", category: "Fruit" },
  { id: 45, name: "Breadcrumbs", category: "Grain" },
  { id: 46, name: "Cream", category: "Dairy" },
  { id: 47, name: "Sour Cream", category: "Dairy" },
  { id: 48, name: "Water", category: "Other" },
  { id: 49, name: "Beef Steak", category: "Meat" },
  { id: 50, name: "Shrimp", category: "Seafood" },
  { id: 51, name: "Tuna", category: "Seafood" },
  { id: 52, name: "Salmon", category: "Seafood" },
  { id: 53, name: "Bacon", category: "Meat" },
  { id: 54, name: "Ham", category: "Meat" },
  { id: 55, name: "Sausage", category: "Other" },
  { id: 56, name: "Tofu", category: "Other" },
  { id: 57, name: "Chickpeas", category: "Vegetable" },
  { id: 58, name: "Kidney Beans", category: "Vegetable" },
  { id: 59, name: "Lentils", category: "Other" },
  { id: 60, name: "Black Beans", category: "Vegetable" },
  { id: 61, name: "Cabbage", category: "Vegetable" },
  { id: 62, name: "Red Cabbage", category: "Vegetable" },
  { id: 63, name: "Cauliflower", category: "Vegetable" },
  { id: 64, name: "Avocado", category: "Vegetable" },
  { id: 65, name: "Pineapple", category: "Fruit" },
  { id: 66, name: "Apple", category: "Fruit" },
  { id: 67, name: "Banana", category: "Fruit" },
  { id: 68, name: "Pear", category: "Fruit" },
  { id: 69, name: "Strawberry", category: "Fruit" },
  { id: 70, name: "Blueberry", category: "Fruit" },
  { id: 71, name: "Raspberry", category: "Fruit" },
  { id: 72, name: "Orange", category: "Fruit" },
  { id: 73, name: "Peach", category: "Fruit" },
  { id: 74, name: "Grapes", category: "Fruit" },
  { id: 75, name: "Walnuts", category: "Other" },
  { id: 76, name: "Almonds", category: "Other" },
  { id: 77, name: "Hazelnuts", category: "Other" },
  { id: 78, name: "Peanuts", category: "Other" },
  { id: 79, name: "Cashews", category: "Other" },
  { id: 80, name: "Sunflower Seeds", category: "Other" },
  { id: 81, name: "Pumpkin Seeds", category: "Vegetable" },
  { id: 82, name: "Chia Seeds", category: "Other" },
  { id: 83, name: "Oats", category: "Grain" },
  { id: 84, name: "Cornmeal", category: "Vegetable" },
  { id: 85, name: "Couscous", category: "Grain" },
  { id: 86, name: "Quinoa", category: "Grain" },
  { id: 87, name: "Maple Syrup", category: "Sweetener" },
  { id: 88, name: "Molasses", category: "Sweetener" },
  { id: 89, name: "Jam", category: "Sweetener" },
  { id: 90, name: "Chocolate", category: "Sweetener" },
  { id: 91, name: "Dark Chocolate", category: "Sweetener" },
  { id: 92, name: "Cocoa Powder", category: "Other" },
  { id: 93, name: "Instant Coffee", category: "Other" },
  { id: 94, name: "Tea Leaves", category: "Other" },
  { id: 95, name: "Gelatin", category: "Other" },
  { id: 96, name: "Cornstarch", category: "Vegetable" },
  { id: 97, name: "Yeast", category: "Other" },
  { id: 98, name: "Worcestershire Sauce", category: "Sauce" },
  { id: 99, name: "Vinegar", category: "Sauce" },
  { id: 100, name: "Sesame Oil", category: "Oil" },
  { id: 101, name: "Fish Sauce", category: "Sauce" },
  { id: 102, name: "Sriracha", category: "Sauce" },
  { id: 103, name: "Hot Sauce", category: "Sauce" },
  { id: 104, name: "Pickles", category: "Other" },
  { id: 105, name: "Capers", category: "Other" },
  { id: 106, name: "Olives", category: "Vegetable" },
  { id: 107, name: "Green Beans", category: "Vegetable" },
  { id: 108, name: "Asparagus", category: "Vegetable" },
  { id: 109, name: "Leek", category: "Vegetable" },
  { id: 110, name: "Shallots", category: "Vegetable" },
  { id: 111, name: "Scallions", category: "Vegetable" },
  { id: 112, name: "Celery", category: "Vegetable" },
  { id: 113, name: "Eggplant", category: "Vegetable" },
  { id: 114, name: "Pumpkin", category: "Vegetable" },
  { id: 115, name: "Sweet Potato", category: "Vegetable" },
  { id: 116, name: "Radish", category: "Vegetable" },
  { id: 117, name: "Beetroot", category: "Vegetable" },
  { id: 118, name: "Turnip", category: "Vegetable" },
  { id: 119, name: "Artichoke", category: "Vegetable" },
  { id: 120, name: "Brussels Sprouts", category: "Vegetable" },
  { id: 121, name: "Fennel", category: "Vegetable" },
  { id: 122, name: "Mango", category: "Fruit" },
  { id: 123, name: "Kiwi", category: "Fruit" },
  { id: 124, name: "Plum", category: "Fruit" },
  { id: 125, name: "Fig", category: "Fruit" },
  { id: 126, name: "Pomegranate", category: "Fruit" },
  { id: 127, name: "Cranberry", category: "Fruit" },
  { id: 128, name: "Coconut", category: "Fruit" },
  { id: 129, name: "Coconut Oil", category: "Fruit" },
  { id: 130, name: "Cream Cheese", category: "Dairy" },
  { id: 131, name: "Ricotta", category: "Dairy" },
  { id: 132, name: "Mozzarella", category: "Dairy" },
  { id: 133, name: "Feta Cheese", category: "Dairy" },
  { id: 134, name: "Parmesan", category: "Dairy" },
  { id: 135, name: "Blue Cheese", category: "Dairy" },
  { id: 136, name: "Goat Cheese", category: "Dairy" },
  { id: 137, name: "Evaporated Milk", category: "Dairy" },
  { id: 138, name: "Condensed Milk", category: "Dairy" },
  { id: 139, name: "Buttermilk", category: "Dairy" },
  { id: 140, name: "Whipping Cream", category: "Dairy" },
  { id: 141, name: "Ice Cream", category: "Dairy" },
  { id: 142, name: "Puff Pastry", category: "Grain" },
  { id: 143, name: "Pie Crust", category: "Grain" },
  { id: 144, name: "Tortilla", category: "Grain" },
  { id: 145, name: "Naan Bread", category: "Grain" },
  { id: 146, name: "Pita Bread", category: "Grain" },
  { id: 147, name: "Cornflakes", category: "Vegetable" },
  { id: 148, name: "Wheat Flour", category: "Grain" },
  { id: 149, name: "Barley", category: "Grain" },
  { id: 150, name: "Celeriac", category: "Other" },
  { id: 151, name: "Kale", category: "Vegetable" },
  { id: 152, name: "Arugula", category: "Vegetable" },
  { id: 153, name: "Iceberg Lettuce", category: "Vegetable" },
  { id: 154, name: "Romaine Lettuce", category: "Vegetable" },
  { id: 155, name: "Watercress", category: "Vegetable" },
  { id: 156, name: "Apricot", category: "Fruit" },
  { id: 157, name: "Clarified Butter", category: "Dairy" },
  { id: 158, name: "Ghee", category: "Oil" },
  { id: 159, name: "Camembert", category: "Dairy" },
  { id: 160, name: "Brie", category: "Dairy" },
  { id: 161, name: "Prosciutto", category: "Meat" },
  { id: 162, name: "Salami", category: "Meat" },
  { id: 163, name: "Turkey Breast", category: "Meat" },
  { id: 164, name: "Lamb", category: "Meat" },
  { id: 165, name: "Duck", category: "Meat" },
  { id: 166, name: "Quail Eggs", category: "Dairy" },
  { id: 167, name: "Anchovies", category: "Seafood" },
  { id: 168, name: "Clams", category: "Seafood" },
  { id: 169, name: "Scallops", category: "Seafood" },
  { id: 170, name: "Mussels", category: "Seafood" },
  { id: 171, name: "Octopus", category: "Seafood" },
  { id: 171, name: "Apricot", category: "Fruit" },
  { id: 172, name: "Clarified Butter", category: "Oil" },
  { id: 173, name: "Ghee", category: "Oil" },
  { id: 174, name: "Camembert", category: "Dairy" },
  { id: 175, name: "Brie", category: "Dairy" },
  { id: 176, name: "Prosciutto", category: "Meat" },
  { id: 177, name: "Salami", category: "Meat" },
  { id: 178, name: "Turkey Breast", category: "Meat" },
  { id: 179, name: "Lamb", category: "Meat" },
  { id: 180, name: "Duck", category: "Meat" },
  { id: 181, name: "Quail Eggs", category: "Dairy" },
  { id: 182, name: "Anchovies", category: "Seafood" },
  { id: 183, name: "Clams", category: "Seafood" },
  { id: 184, name: "Edamame", category: "Vegetable" },
  { id: 185, name: "Tempeh", category: "Other" },
  { id: 186, name: "Paneer", category: "Dairy" },
  { id: 187, name: "Buckwheat", category: "Grain" },
  { id: 188, name: "Millet", category: "Grain" },
  { id: 189, name: "Spaghetti", category: "Grain" },
  { id: 190, name: "Macaroni", category: "Grain" },
  { id: 191, name: "Penne", category: "Grain" },
  { id: 192, name: "Fusilli", category: "Grain" },
  { id: 193, name: "Tagliatelle", category: "Grain" },
  { id: 194, name: "Lasagna Sheets", category: "Grain" },
  { id: 195, name: "Ravioli", category: "Grain" },
  { id: 196, name: "Tortellini", category: "Grain" },
  { id: 197, name: "Rice Noodles", category: "Grain" },
  { id: 198, name: "Glass Noodles", category: "Grain" },
  { id: 199, name: "Instant Noodles", category: "Grain" },
  { id: 200, name: "Canned Corn", category: "Vegetable" },
  { id: 201, name: "Canned Peas", category: "Vegetable" },
  { id: 202, name: "Canned Tuna", category: "Seafood" },
  { id: 203, name: "Canned Beans", category: "Vegetable" },
  { id: 204, name: "Canned Tomatoes", category: "Vegetable" },
  { id: 205, name: "Pickled Cucumber", category: "Vegetable" },
  { id: 206, name: "Pickled Garlic", category: "Vegetable" },
  { id: 207, name: "Sun-Dried Tomatoes", category: "Vegetable" },
  { id: 208, name: "Tomato Paste", category: "Sauce" },
  { id: 209, name: "Tomato Sauce", category: "Sauce" },
  { id: 210, name: "BBQ Sauce", category: "Sauce" },
  { id: 211, name: "Pesto", category: "Sauce" },
  { id: 212, name: "Bechamel Sauce", category: "Sauce" },
  { id: 213, name: "Chili Sauce", category: "Sauce" },
  { id: 214, name: "Ranch Dressing", category: "Sauce" },
  { id: 215, name: "Caesar Dressing", category: "Sauce" },
  { id: 216, name: "Tartar Sauce", category: "Sauce" },
  { id: 217, name: "Miso Paste", category: "Other" },
  { id: 218, name: "Curry Paste", category: "Spice" },
  { id: 219, name: "Curry Powder", category: "Spice" },
  { id: 220, name: "Paprika", category: "Spice" },
  { id: 221, name: "Turmeric", category: "Spice" },
  { id: 222, name: "Cumin", category: "Spice" },
  { id: 223, name: "Nutmeg", category: "Spice" },
  { id: 224, name: "Cardamom", category: "Spice" },
  { id: 225, name: "Star Anise", category: "Spice" },
  { id: 226, name: "Bay Leaf", category: "Spice" },
  { id: 227, name: "Allspice", category: "Spice" },
  { id: 228, name: "Clove", category: "Spice" },
  { id: 229, name: "White Pepper", category: "Spice" },
  { id: 230, name: "Black Sesame", category: "Spice" },
  { id: 231, name: "Wasabi", category: "Spice" },
  { id: 232, name: "Horseradish", category: "Spice" },
  { id: 233, name: "Tamarind", category: "Other" },
  { id: 234, name: "Rose Water", category: "Other" },
  { id: 235, name: "Orange Blossom Water", category: "Other" },
  { id: 236, name: "Saffron", category: "Spice" },
  { id: 237, name: "Gelatin Sheets", category: "Other" },
  { id: 238, name: "Agar Agar", category: "Other" },
  { id: 239, name: "Poppy Seeds", category: "Spice" },
  { id: 240, name: "Caraway Seeds", category: "Spice" },
  { id: 241, name: "Marjoram", category: "Spice" },
  { id: 242, name: "Savory", category: "Spice" },
  { id: 243, name: "Fenugreek", category: "Spice" },
  { id: 244, name: "Mustard Seeds", category: "Spice" },
  { id: 245, name: "Coriander Seeds", category: "Spice" },
  { id: 246, name: "Coriander Leaves", category: "Spice" },
  { id: 247, name: "Lemongrass", category: "Spice" },
  { id: 248, name: "Galangal", category: "Spice" },
  { id: 249, name: "Kaffir Lime Leaves", category: "Spice" },
  { id: 250, name: "Curry Leaves", category: "Spice" }
];